//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMDBEntities : DbContext
    {
        public HRMDBEntities()
            : base("name=HRMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<ORGANIZATION> ORGANIZATION { get; set; }
        public virtual DbSet<POSITION> POSITION { get; set; }
        public virtual DbSet<SEX> SEX { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
