//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM5
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.USERS = new HashSet<USERS>();
        }
    
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public byte[] Photo { get; set; }
        public byte[] CurriculumVitae { get; set; }
        public string CurriculumVitaeType { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string IndentifyNumber { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> SexID { get; set; }
    
        public virtual ORGANIZATION ORGANIZATION { get; set; }
        public virtual POSITION POSITION { get; set; }
        public virtual SEX SEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS> USERS { get; set; }
    }
}
