//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM7
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int UsersID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Discription { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ma_moi { get; set; }

        public bool Remember {  get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
