//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinesProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Medicines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicines()
        {
            this.Storages = new HashSet<Storages>();
        }
    
        public int MedicineID { get; set; }
        [Required(ErrorMessage = "Trade name is required.")]
        [StringLength(100, ErrorMessage = "Trade name must be under 100 characters.")]
        public string TradeName { get; set; }
        [Required(ErrorMessage = "Active ingredient is required.")]
        [StringLength(100, ErrorMessage = "Active ingredient must be under 100 characters.")]
        public string ActiveIngredient { get; set; }
        [Required(ErrorMessage = "Category is required.")]
        public int CategoryID { get; set; }
        [Required(ErrorMessage = "Unit is required.")]
        [StringLength(50)]
        public string Unit { get; set; }
        [Required(ErrorMessage = "Concentration is required.")]
        [StringLength(50)]
        public string Concentration { get; set; }
        [Required(ErrorMessage = "Form is required.")]
        [StringLength(50)]
        public string Form { get; set; }
        [Required(ErrorMessage = "Sale price is required.")]
        [Range(0, double.MaxValue, ErrorMessage = "Sale price must be a non-negative number.")]
        [DisplayFormat(DataFormatString = "{0:0}", ApplyFormatInEditMode = true)] // ??nh d?ng s? nguyên 4800
        public decimal SalePrice { get; set; }
        [Required(ErrorMessage = "Manufacturer is required.")]
        public int ManufacturerID { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual MedicineCategories MedicineCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storages> Storages { get; set; }
    }
}
