//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinesProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Storages
    {
        public int StorageID { get; set; }
        [Required(ErrorMessage = "Trade name is required.")]
        public string ReceiptCode { get; set; }
        [Required(ErrorMessage = "Batch number is required")]
        public string BatchNumber { get; set; }
        [Required(ErrorMessage = "Medicine is required")]
        public int MedicineID { get; set; }
        [Required(ErrorMessage = "Manufacture date is required")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime ManufactureDate { get; set; }
        [Required(ErrorMessage = "Expiry date is required")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime ExpiryDate { get; set; }
        [Required(ErrorMessage = "Quantity is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Quantity must be greater than 0")]
        public int Quantity { get; set; }
        [Required(ErrorMessage = "Import price is required.")]
        [Range(0, double.MaxValue, ErrorMessage = "Import price must be a non-negative number.")]
        [DisplayFormat(DataFormatString = "{0:0}", ApplyFormatInEditMode = true)] // use format 13.000
        public decimal ImportPrice { get; set; }
        [Required(ErrorMessage = "Supplier is required")]
        public int SupplierID { get; set; }
        [Required(ErrorMessage = "Import date is required")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime ImportDate { get; set; }
        public virtual Medicines Medicines { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
